spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://cognito-idp.us-east-2.amazonaws.com/us-east-2_7pjOedHut
          jwk-set-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_7pjOedHut/.well-known/jwks.json