version: 2.1

orbs:
  maven: circleci/maven@1.0.2

workflows:
  maven_test:
    jobs:
      - maven/test:  # checkout, build, test, and upload test result
          executor:
            name: maven/default
            tag: '14.0'
      - publish-docker:
          requires:
            - maven/test
jobs:
  publish-docker:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: Publish Docker image with Jib
          command: |
            ./mvnw compile jib:build -B -DskipTests=true
