version: 2.1

orbs:
  maven: circleci/maven@1.0.2

workflows:
  maven_test:
    jobs:
      - maven/test:  # checkout, build, test, and upload test result
          executor:
            name: maven/default
            tag: '14.0'
      - upload-artifact:
          requires:
            - maven/test
      - publish-docker:
          requires:
            - upload-artifact
jobs:
  upload-artifact:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt u "userservice*/*.jar" backend --build-name=userservice --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce userservice $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp userservice $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
  publish-docker:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: Publish Docker image with Jib
          command: |
            ./mvnw compile jib:build -B -DskipTests=true
